; Sample configuration file
 
[data_initial]

#Atomic species 87Sr/171Yb/199Hg/88Sr/174Yb/111Cd/24Mg
Atom=87Sr

#Default number of pairs of magnets
Npm=12

#Laser power [mW]
P=30

#Braking distance in [cm]
z=25

#Capture & final target velocities [m/s]            
V_cap=400       
V_fin=40

#Detuning [MHz]
d0 =-430

#Beam waist (radius) [mm]
w0=3.5

#Cylindric Magnets dimensions [mm]
mag_diam=20
mag_heig=10

#Magnets remanescence [mT]
Tmagz=1300

#------ OTHER PARAMETERS not modifiable in GUI ------

#External tube radius (limit for magnets getting closer) [mm]
ext_tube_radius=9.6
safety_margin=6 

#Minimum magnet displacement [mm]
displ=0.1

# Maximum number of iterations for each magnet optimization process [#]
max_iters=30

#Separation first and last magnets [mm]
sep_ini=2.5
sep_last=2.5

#Max vertical position for magnets to separate from atomic axis
max_V_position = 150.0

#Eta parameter for full s_max usage [a.u. 0-1]
eta=0.70

[atomic_kinetics]

#Number of velocities to simulate from 0 to a 10% greater than V_cap
N_vel=15

#Number of time steps for the time vector
Nt=20e3

#Resolution of time steps [s]
dt=9e-7

#Atoms initial z_position [mm]
atoms_initial_z_position=-75

#Distance to velocity measurement [cm]
dist_veloc_meas=12.0

#Consider usage of sigma+ light [Bool]
use_sigma_plus = True


[atomic_parameter_87Sr]

#87Sr mass [u]
m = 86.9089

#1S0-1P1 transition lambda [m]
WL_ge = 4.6086212862e-07

#1S0-1P1 transition width [Hz]
gamma = 30.24e6

#Rate mu_eff/mu_B (Bohr magneton) [a.u]
mu_eff = -0.9994071129074684


[atomic_parameter_171Yb]

#171Yb mass [u]
m = 170.9363258

#1S0-1P1 transition lambda [m]
WL_ge = 3.9900005912113637e-07

#1S0-1P1 transition width [Hz]
gamma = 28.999622180e06


#Rate mu_eff/mu_B (Bohr magneton) [a.u]
mu_eff = -1.035
 

[atomic_parameter_199Hg]

#199Hg mass [u]
m = 198.96828

#1S0-3P1 intercombination cooling transition lambda [m]
WL_ge = 2.53727e-07

#1S0-3P1 transition width [Hz]
gamma = 1.27e6

#Rate mu_eff/mu_B (Bohr magneton) [a.u]
# El factor de Landé g_J para el estado 3P1 es ~1.5
mu_eff = -1.5


[atomic_parameter_88Sr]

#88Sr mass [u]
m = 87.9056

#1S0-1P1 transition lambda [m]
WL_ge = 4.608621e-07

#1S0-1P1 transition width [Hz]
gamma = 30.24e6


#Rate mu_eff/mu_B (Bohr magneton) [a.u]
mu_eff = -1.00


[atomic_parameter_174Yb]

#174Yb mass [u]
m = 173.9388

#1S0-1P1 transition lambda [m]
WL_ge = 3.98911e-07

#1S0-1P1 transition width [Hz]
gamma = 29.1e6


#Rate mu_eff/mu_B (Bohr magneton) [a.u]
mu_eff = -1.000


[atomic_parameter_111Cd]

#111Cd mass [u]
m = 110.90418

#1S0-1P1 main cooling transition lambda [m]
WL_ge = 2.288022e-07

#1S0-1P1 transition width [Hz]
gamma = 90.2e6

#Rate mu_eff/mu_B (Bohr magneton) [a.u]
mu_eff = -1.0


[atomic_parameter_24Mg]

#24Mg mass [u]
m = 23.98504

#1S0-1P1 main cooling transition lambda [m]
WL_ge = 2.852127e-07

#1S0-1P1 transition width [Hz]
gamma = 78.1e6

#Rate mu_eff/mu_B (Bohr magneton) [a.u]
mu_eff = -1.0


[number of points to calculate B]
B_points=1001
B_points_additional=400

[scale_factor_B]
# Value to compensate effects of excessive B field out of deceleration zone
scale_factor_B = 1.08

[save_graphics]

#Size of title, axis labels, legends and axis ticks large/medium/small
graphics_fontsize = small
